<?php

class LuceneController extends Zend_Controller_Action
{
    public function indexAction()
    {
        $doc = new Zend_Search_Lucene_Document();
        $doc->addField(Zend_Search_Lucene_Field::Keyword('doctype', 'autogenerated'));
        $doc->addField(Zend_Search_Lucene_Field::UnIndexed('created', time()));
        $doc->addField(Zend_Search_Lucene_Field::Text('annotate', 'Doc annotate text'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('contents', 'Doc content'));

        $index = Zend_Search_Lucene::create(APPLICATION_PATH . '/../data/index');
        $index->addDocument($doc);
    }
}